mainTitle: '§e§l猜拳 §6第-§b%s§6-页'
showName: '§b由 §c%s §b发起的猜拳游戏!'
# 税收
tax: 0.9
showInfo:
  - '§7拳手 §c{0} §7已经出拳了，请猜猜ta出的是什么?'
  - '§7对方押注了 {1} 金币！'
  - '§7你必须有 {1} 金币才能和他进行对等猜拳！'
  - '§7规则: §e克制关系§d>>>§a石头->§b剪刀->§6布->§d石头'
  - '    §7胜利方将获得失败方押注的金币§f>> §c税(§f10%§c)后 §e{2} §7~'
  - '    §7平局则双方互不损失~'

tied: '§e[猜拳结果] §a{0}§c⚔§b{1} §7平局!'
win: '§e[猜拳结果] §a{0}§c⚔§b{1} §a胜利!'
lose: '§e[猜拳结果] §a{0}§c⚔§b{1} §c失败!'
invalid: '§c这场猜拳游戏已经被竞猜了~你可以参与其它猜拳或自己发起一场!'
self: '§c你不能自己和自己猜拳!'
launch1: '§e请输入金额……'
launch2: '§e发起猜拳成功!'
vault1: '§c你当前的金币不够与 {0} 进行对等猜拳， 你至少需要拥有 {1} 金币!'
vault2: '§c你没有这么多金额 {0}/{1}，来发起猜拳，请重新发起！'
vault3: '§c请输入一个正确的数值,请重新发起!'